name: fakenews
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.11.4=hca03da5_0
  - expat=2.7.3=h982b769_0
  - libcxx=20.1.8=hd7fd590_1
  - libffi=3.4.4=hca03da5_1
  - libzlib=1.3.1=h5f15de7_0
  - ncurses=6.5=hee39554_0
  - openssl=3.0.18=h9b4081a_0
  - pip=25.3=pyhc872135_0
  - python=3.10.19=hf701271_0
  - readline=8.3=h0b18652_0
  - setuptools=80.9.0=py310hca03da5_0
  - sqlite=3.51.0=hab6afd1_0
  - tk=8.6.15=hcd8a7d5_0
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py310hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - pip:
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.11.0
      - beautifulsoup4==4.14.2
      - blis==1.3.3
      - catalogue==2.0.10
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.3.1
      - cloudpathlib==0.23.0
      - confection==0.1.5
      - cssselect==1.3.0
      - cymem==2.0.13
      - dnspython==2.8.0
      - email-validator==2.3.0
      - en-core-web-sm==3.8.0
      - exceptiongroup==1.3.1
      - fastapi==0.122.0
      - feedfinder2==0.0.4
      - feedparser==6.0.12
      - filelock==3.20.0
      - fsspec==2025.10.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - huggingface-hub==0.36.0
      - idna==3.11
      - jieba3k==0.35.1
      - jinja2==3.1.6
      - joblib==1.5.2
      - lxml==6.0.2
      - lxml-html-clean==0.4.3
      - markupsafe==3.0.3
      - mpmath==1.3.0
      - murmurhash==1.0.15
      - networkx==3.4.2
      - newspaper3k==0.2.8
      - nltk==3.9.2
      - numpy==2.2.6
      - oauthlib==3.3.1
      - packaging==25.0
      - pillow==12.0.0
      - preshed==3.0.12
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - pyyaml==6.0.3
      - rake-nltk==1.0.6
      - regex==2025.11.3
      - requests==2.32.5
      - requests-file==3.0.1
      - requests-oauthlib==2.0.0
      - safetensors==0.7.0
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - sentence-transformers==5.1.2
      - sgmllib3k==1.0.0
      - six==1.17.0
      - smart-open==7.5.0
      - sniffio==1.3.1
      - soupsieve==2.8
      - spacy==3.8.11
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.5.2
      - starlette==0.50.0
      - sympy==1.14.0
      - thinc==8.3.10
      - threadpoolctl==3.6.0
      - tinysegmenter==0.3
      - tldextract==5.3.0
      - tokenizers==0.22.1
      - torch==2.9.1
      - tqdm==4.67.1
      - transformers==4.57.1
      - tweepy==4.16.0
      - typer-slim==0.20.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - urllib3==2.5.0
      - uvicorn==0.38.0
      - wasabi==1.1.3
      - weasel==0.4.3
      - wrapt==2.0.1
prefix: /opt/anaconda3/envs/fakenews
